Create httpclient instance with httpclientfactory
SenseNet/sn-client-dotnet pull request #134
Opened 2024-03-19 06:41 UTC by hashtagnulla

2024-03-19 06:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SenseNet/sn-client-dotnet?pullRequest=134) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SenseNet/sn-client-dotnet?pullRequest=134) before we can accept your contribution.<br/><hr/>**Viktor Nagy** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SenseNet/sn-client-dotnet?pullRequest=134) it.</sub>

2024-03-19 06:56 UTC, tusmester requested changes

2024-03-19 06:56 UTC, tusmester commented on src/SenseNet.Client/DefaultRestCaller.cs
> +        using var client = _httpClientFactory.CreateClient();
We should pass the handler that we created above if possible.

2024-03-19 06:56 UTC, tusmester commented on src/SenseNet.Client.DemoMvc/Program.cs
> +builder.Services.AddHttpClient();
We should move this inside the main entry point (AddSenseNetClient) so that developers do not have to call this manually.

2024-03-19 18:21 UTC, kavics approved these changes

2024-03-20 08:22 UTC, kavics approved these changes

2024-03-20 09:04 UTC, tusmester approved these changes

2024-03-20 13:47 UTC, merged